name: AnswerBot
description: Instant answers, powered by AI

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: 4.0.3

  flutter_bloc: 8.1.2
  equatable: 2.0.5

  http: 0.13.5
  json_annotation: 4.8.0
  freezed_annotation: 2.2.0

  flutter_launcher_icons: 0.12.0
  flutter_native_splash: 2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1
  build_runner: 2.3.3
  json_serializable: 6.6.1
  freezed: 2.3.2

flutter:
  uses-material-design: true
